[tool.black]
line-length = 88
target-version = ['py38']

[tool.flake8]
max-line-length = 88

[tool.pylint.messages_control]
max-line-length = 88
max-args = 7
max-locals = 17
disable = [
    "logging-fstring-interpolation",
    "unused-argument",
]
