apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: resourceforger-operator
resources:
  - ../../bases
  - namespace.yaml
images:
  - name: KOPF_OPERATOR_IMAGE
    newName: registry.hub.docker.com/fkawala/kopf-forger
    newTag: v1.0.0
