apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: resourceforgers.infomaniak.com
spec:
  scope: Namespaced
  group: infomaniak.com
  names:
    kind: ResourceForger
    plural: resourceforgers
    singular: resourceforger
    shortNames:
      - rf
      - rfs
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                targetNamespaces:
                  type: array
                  maxItems: 25
                  items:
                    type: string
                    maxLength: 253
                originalResources:
                  type: array
                  items:
                    type: object
                    x-kubernetes-embedded-resources: true
                    x-kubernetes-preserve-unknown-fields: true
